import {useState} from 'react';
import {api} from './api';
import './community-gallery.css';
import type {State} from './types';

export type GalleryComment={id:string;name:string;personaId:string;text:string;time:number;parentId:string|null;kind:string;deleted?:boolean};
export type GalleryPost={id:string;title?:string;category?:string;name:string;text:string;time:number;kind:string;comments?:GalleryComment[];votes?:string[]};
const titleOf=(p:GalleryPost)=>p.title||p.text.split('\n')[0].slice(0,70);
export function CommunityGallery({state,onError}:{state:State;onError:(message:string)=>void}){
  const [selected,setSelected]=useState<string|null>(null),[writing,setWriting]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[category,setCategory]=useState('자유'),[filter,setFilter]=useState('전체글'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[comment,setComment]=useState(''),[parent,setParent]=useState<string|null>(null),[pending,setPending]=useState(false);
  const posts:GalleryPost[]=state.audience.posts,post=posts.find(p=>p.id===selected),limit=20;
  const list=posts.filter(p=>(filter==='전체글'||(filter==='추천글'?(p.votes?.length||0)>0:(p.category||(p.kind==='ai'?'후기':'자유'))===filter))&&(!query||(titleOf(p)+' '+p.text+' '+p.name).toLowerCase().includes(query.toLowerCase()))).slice().sort((a,b)=>filter==='추천글'?(b.votes?.length||0)-(a.votes?.length||0)||b.time-a.time:b.time-a.time);
  const currentPage=Math.min(page,Math.max(0,Math.ceil(list.length/limit)-1));
  async function send(path:string,value?:unknown,method?:string){if(pending)return;setPending(true);try{return await api(path,value,method);}catch(e){onError(e instanceof Error?e.message:'게시판 처리 실패');}finally{setPending(false);}}
  function select(id:string|null){setSelected(id);setParent(null);setComment('');setWriting(false);}

  return <section className="panel community-gallery" aria-label="방송 갤러리">
    <header className="gallery-heading"><div><span className="eyebrow">Nagneon COMMUNITY</span><h2>{state.settings.streamer} 갤러리</h2><p>앱이 켜져 있으면 관객이 스스로 들러 이야기합니다. 방송 응답이 먼저예요.</p></div><button className="primary" onClick={()=>{select(null);setWriting(true);}}>글쓰기</button></header>
    <div className="gallery-toolbar"><div className="gallery-tabs" role="group" aria-label="게시글 분류">{['전체글','추천글','공지','후기','질문','자유'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'selected':''} onClick={()=>{setFilter(f);setPage(0);}}>{f}</button>)}</div><input aria-label="갤러리 검색" placeholder="제목 · 내용 · 글쓴이 검색" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></div>
    {writing&&<form className="gallery-write" onSubmit={async e=>{e.preventDefault();const result=await send('community/post',{title,text:body,category});if(result){setTitle('');setBody('');setWriting(false);select((result as GalleryPost).id);}}}><div className="inline-form"><select aria-label="새 게시글 말머리" value={category} onChange={e=>setCategory(e.target.value)}>{['자유','후기','질문','공지'].map(c=><option key={c}>{c}</option>)}</select><input aria-label="게시글 제목" placeholder="제목" value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} required/></div><textarea aria-label="게시글 내용" placeholder="오늘 방송에서 나누고 싶은 이야기" value={body} onChange={e=>setBody(e.target.value)} maxLength={1000} required/><div className="inline-form"><button className="primary" disabled={pending||!title.trim()||!body.trim()}>등록</button><button type="button" className="secondary" onClick={()=>setWriting(false)}>취소</button></div></form>}
    {post&&<article className="gallery-detail"><button className="text-button" onClick={()=>select(null)}>← 목록으로</button><h3>[{post.category||(post.kind==='ai'?'후기':'자유')}] {titleOf(post)}</h3><div className="gallery-meta">{post.name} · {post.kind==='ai'?'관객':'스트리머'} · {new Date(post.time).toLocaleString('ko-KR')}</div><p className="gallery-body">{post.text}</p><div className="gallery-vote"><button className="secondary" aria-pressed={post.votes?.includes('streamer')||false} disabled={pending} onClick={()=>void send(`community/posts/${post.id}/recommend`,{recommended:!post.votes?.includes('streamer')})}>추천 {post.votes?.length||0}</button><button className="text-button" disabled={pending} onClick={async()=>{if(await send(`community/posts/${post.id}`,undefined,'DELETE'))select(null);}}>게시글 삭제</button></div><h4>댓글 {(post.comments||[]).length}</h4><div className="gallery-comments">{(post.comments||[]).filter(c=>!c.parentId).map(c=><div className="gallery-comment" key={c.id}><div><b>{c.name}</b><small>{new Date(c.time).toLocaleString('ko-KR')}</small></div><p>{c.text}</p>{!c.deleted&&<div className="inline-form"><button className="text-button" onClick={()=>setParent(c.id)}>답글</button><button className="text-button" disabled={pending} onClick={()=>void send(`community/posts/${post.id}/comments/${c.id}`,undefined,'DELETE')}>삭제</button></div>}{(post.comments||[]).filter(r=>r.parentId===c.id).map(r=><div className="gallery-reply" key={r.id}><b>↳ {r.name}</b><p>{r.text}</p>{!r.deleted&&<button className="text-button" disabled={pending} onClick={()=>void send(`community/posts/${post.id}/comments/${r.id}`,undefined,'DELETE')}>삭제</button>}</div>)}</div>)}</div>{parent&&<button className="text-button" onClick={()=>setParent(null)}>{post.comments?.find(c=>c.id===parent)?.name}에게 답글 · 취소</button>}<form onSubmit={async e=>{e.preventDefault();if(await send(`community/posts/${post.id}/comments`,{text:comment,parentId:parent})){setComment('');setParent(null);}}}><textarea aria-label="갤러리 댓글" value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} placeholder="댓글을 남겨보세요"/><div className="inline-form"><button className="primary" disabled={pending||!comment.trim()}>댓글 등록</button></div></form></article>}
    <div className="gallery-table-wrap"><table className="gallery-table"><thead><tr><th>번호</th><th>말머리</th><th>제목</th><th>글쓴이</th><th>작성일</th><th>추천</th></tr></thead><tbody>{list.slice(currentPage*limit,(currentPage+1)*limit).map(p=><tr key={p.id} className={p.id===selected?'selected':''}><td>{posts.findIndex(x=>x.id===p.id)+1}</td><td>{p.category||(p.kind==='ai'?'후기':'자유')}</td><td><button onClick={()=>select(p.id)}>{titleOf(p)} <span className="gallery-count">[{p.comments?.length||0}]</span></button></td><td>{p.name}</td><td>{new Date(p.time).toLocaleDateString('ko-KR')}</td><td>{p.votes?.length||0}</td></tr>)}</tbody></table>{!list.length&&<p className="gallery-empty">아직 게시글이 없습니다. 첫 이야기를 남겨보세요.</p>}</div><footer className="gallery-footer"><button className="secondary" disabled={!currentPage} onClick={()=>setPage(currentPage-1)}>이전</button><span>{currentPage+1} / {Math.max(1,Math.ceil(list.length/limit))}</span><button className="secondary" disabled={(currentPage+1)*limit>=list.length} onClick={()=>setPage(currentPage+1)}>다음</button></footer>
  </section>;
}
