import {useEffect,useState} from 'react';
import {BookMarked,ChevronLeft,ChevronRight,Pin,Search,Trash2} from 'lucide-react';
import {api} from './api';
import type {State} from './types';
import './memories.css';

type Entry={transcription?:{source:"microphone";correction?:{text:string}};id:string;sessionId:string;at:number;personaId:string;name:string;text:string;witnesses:string[];fictional:boolean;title:string;pinned:boolean};
type Page={entries:Entry[];total:number;offset:number;count:number;pinned:number;limit:number;pinLimit:number};
export function ConversationMemories({state,onError}:{state:State;onError:(text:string)=>void}){
  const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[viewer,setViewer]=useState(''),[pinned,setPinned]=useState(false),[offset,setOffset]=useState(0),[page,setPage]=useState<Page|null>(null),[pending,setPending]=useState(false),[deleting,setDeleting]=useState(''),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false);
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setOffset(0);},250);return()=>clearTimeout(timer);},[query]);
  useEffect(()=>{let disposed=false;setLoading(true);const params=new URLSearchParams({query:search,viewerId:viewer,pinned:String(pinned),offset:String(offset)});void api<Page>('journal?'+params,undefined,'GET').then(result=>{if(!disposed){if(!result.entries.length&&offset>0)setOffset(Math.max(0,offset-30));else setPage(result);}}).catch(e=>{if(!disposed)onError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[search,viewer,pinned,offset,state.journal?.revision,refresh]);
  async function change(entry:Entry,remove=false){setPending(true);try{await api('journal/'+entry.id+(remove?'':'/pin'),remove?undefined:{pinned:!entry.pinned},remove?'DELETE':'POST');setDeleting('');setRefresh(n=>n+1);}catch(e){onError(e instanceof Error?e.message:'대화 기억을 변경하지 못했습니다.');}finally{setPending(false);}}
  return <section className="panel memory-journal" aria-label="함께 나눈 말">
    <header className="memory-heading"><div><span className="eyebrow">REMEMBERED TOGETHER</span><h2><BookMarked size={23}/> 함께 들은 말, 오래 남기기.</h2><p>작은 취향과 우리만의 약속. 누가 함께 들었는지 남기고, 다음 방송에서 다시 떠올려요.</p></div><span className="status-pill">{state.journal?.count||0}개의 말</span></header>
    <div className="memory-filters"><label className="memory-search"><span><Search size={15}/> 대화 찾기</span><input aria-label="대화 기억 검색" placeholder="약속, 구호, 취향을 찾아보세요" value={query} maxLength={300} onChange={e=>setQuery(e.target.value)}/></label><label>함께 들은 관객<select aria-label="기억을 가진 관객" value={viewer} onChange={e=>{setViewer(e.target.value);setOffset(0);}}><option value="">모든 관객</option>{state.settings.personas.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={pinned} onChange={e=>{setPinned(e.target.checked);setOffset(0);}}/> 고정한 말만</label></div>
    <p className="field-note">공개 채팅만 기록해요. 당시 함께 있던 관객의 기억으로 이어집니다. 최대 4,000개를 보관하고, 고정한 100개는 오래돼도 유지해요. 비공개 인터뷰와 속마음은 이곳에 섞이지 않아요.</p>
    <div className="memory-list" aria-busy={loading}>
      {!page?.entries.length&&<div className="memory-empty"><BookMarked size={28}/><h3>{search||viewer||pinned?'조건에 맞는 말이 없어요':'첫 번째 기억을 기다려요'}</h3><p>{search||viewer||pinned?'검색어나 관객을 바꿔서 다시 찾아보세요.':'AI 방송에서 인사를 건네보세요. 함께 나눈 말부터 기록이 시작돼요.'}</p></div>}
      {page?.entries.map(entry=><article key={entry.id} className="memory-entry"><div className="memory-meta"><b>{entry.name}</b><time dateTime={new Date(entry.at).toISOString()}>{new Date(entry.at).toLocaleString('ko-KR')}</time>{entry.fictional&&<span className="status-pill">가상 기획 방송</span>}{entry.pinned&&<span className="memory-pin"><Pin size={12}/> 오래 간직할 말</span>}</div><blockquote>{entry.transcription?.correction?.text||entry.text}</blockquote>{entry.transcription?.correction&&<details className="transcript-origin"><summary>음성 교정 · 인식 원문 보기</summary><p>{entry.text}</p></details>}<p className="memory-source">{entry.title} · 함께 들은 관객 {entry.witnesses.map(id=>state.settings.personas.find(p=>p.id===id)?.name||id).join(', ')||'없음'}</p><div className="memory-actions"><button className="text-button" aria-label={(entry.pinned?'고정 해제: ':'기억 고정: ')+entry.name+' '+entry.text.slice(0,24)} disabled={pending} onClick={()=>void change(entry)}><Pin size={14}/>{entry.pinned?'고정 해제':'오래 간직하기'}</button>{deleting===entry.id?<><span>이 기억과 원본 채팅을 지울까요?</span><button className="text-button" disabled={pending||state.busy} onClick={()=>void change(entry,true)}>지우기</button><button className="text-button" disabled={pending} onClick={()=>setDeleting('')}>취소</button></>:<button className="text-button" disabled={pending||state.busy} onClick={()=>setDeleting(entry.id)} aria-label={'대화 기억 삭제: '+entry.name+' '+entry.text.slice(0,24)}><Trash2 size={14}/> 지우기</button>}</div></article>)}
    </div>
    <footer className="memory-footer"><span>{page?.total||0}개 중 {page?.entries.length?offset+1:0}–{offset+(page?.entries.length||0)} · 고정 {page?.pinned||0}/100</span><div><button className="icon" aria-label="이전 기억 페이지" disabled={!offset||loading} onClick={()=>setOffset(Math.max(0,offset-30))}><ChevronLeft size={17}/></button><button className="icon" aria-label="다음 기억 페이지" disabled={!page||offset+30>=page.total||loading} onClick={()=>setOffset(offset+30)}><ChevronRight size={17}/></button></div></footer><p className="field-note">지운 말은 이후 기억 검색에 사용하지 않아요. 핫클립·시즌 기록에 남긴 복사본은 해당 화면에서 별도로 관리할 수 있어요.</p>
  </section>;
}
