import {useEffect,useState} from 'react';
import {Clapperboard,MessageCircle,Reply,Trash2,Play,Headphones} from 'lucide-react';
import {api} from './api';
import {ClipMedia} from './ClipMedia';
import {DonationBadge} from './DonationBadge';
import type {Message,State} from './types';
export type ClipSummary={id:string;title:string;game:string;day:string;sessionId?:string;observedAt?:number;creator?:{id:string;name:string;reason:string};participants:{id:string;name:string}[];commenters?:{id:string;name:string}[];createdAt:number;updatedAt:number;scene:string;source:string;thumbnail:string|null;video:boolean;voice?:boolean;voiceStartedAt?:number;voiceEndedAt?:number;audioLayout?:'mixed'|'separate'|'microphone-only';audio?:boolean;audioEligible?:boolean;audioStartedAt?:number;audioEndedAt?:number;hasAudio?:boolean;videoStartedAt?:number;videoEndedAt?:number;commentCount:number;votes?:string[]};
type Comment={id:string;text:string;name:string;personaId:string;parentId:string|null;kind:string;at:number;deleted?:boolean};
type Clip=ClipSummary&{comments:Comment[];messages:Message[]};
function Thread({items,parentId=null,reply,remove}:{items:Comment[];parentId?:string|null;reply:(item:Comment)=>void;remove:(id:string)=>void}){return <div className={parentId?'clip-replies':'clip-comments'}>{items.filter(c=>c.parentId===parentId).map(c=><article key={c.id}><div className="comment-head"><b>{c.name}</b><small>{c.kind==='ai'?'AI 관객':'스트리머'} · {new Date(c.at).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</small></div><p>{c.text}</p>{!c.deleted&&<div><button className="text-button" onClick={()=>reply(c)}><Reply size={13}/> 대댓글</button><button className="icon" title="댓글 삭제" onClick={()=>remove(c.id)}><Trash2 size={12}/></button></div>}<Thread items={items} parentId={c.id} reply={reply} remove={remove}/></article>)}</div>;}
export function HotClips({state,onError}:{state:State;onError:(text:string)=>void}){
  const [day,setDay]=useState(''),[game,setGame]=useState(''),[viewer,setViewer]=useState(''),[selected,setSelected]=useState<string|null>(null),[clip,setClip]=useState<Clip|null>(null),[text,setText]=useState(''),[parent,setParent]=useState<Comment|null>(null),[pending,setPending]=useState(false);
  const selectedSummary=state.clips.find(c=>c.id===selected);const revision=String(selectedSummary?.updatedAt)+':'+selectedSummary?.commentCount;
  useEffect(()=>{let disposed=false;if(!selected){setClip(null);return;}void api<Clip>('clips/'+selected,undefined,'GET').then(c=>{if(!disposed)setClip(c);}).catch(e=>{if(!disposed)onError(e.message);});return()=>{disposed=true;};},[selected,revision]);
  async function send(path:string,body?:unknown,method?:string){setPending(true);try{const value=await api(path,body,method);return value;}catch(e){onError(e instanceof Error?e.message:'클립 처리 실패');}finally{setPending(false);}}
  const list=state.clips.filter(c=>(!day||c.day===day)&&(!game||c.game===game)&&(!viewer||c.participants.some(p=>p.id===viewer)||c.commenters?.some(p=>p.id===viewer)));
  return <div><section className="panel feature-body"><div className="section-actions"><div><h2>그 순간, 아직 이야기 중.</h2><p>게임의 명장면도, 같이 웃었던 한마디도. 관객들과 다시 만나는 핫클립.</p></div></div><div className="form-grid"><label>방송 일자<input aria-label="클립 방송 일자" type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><label>게임<select value={game} onChange={e=>setGame(e.target.value)}><option value="">모든 게임</option>{[...new Set(state.clips.map(c=>c.game))].map(g=><option key={g}>{g}</option>)}</select></label><label>함께한 관객<select value={viewer} onChange={e=>setViewer(e.target.value)}><option value="">모든 관객</option>{state.settings.personas.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label></div><p className="field-note">관객의 장면 기록을 허용하면 각자의 마음에 든 순간을 남깁니다. 클립 버퍼를 허용하면 최근 구간을 최대 2분 동안 메모리에 보관합니다. 관객이 고른 순간이 남아 있으면 공유한 화면과 연결된 소리를 저장하고, 화면 없이 마이크나 소리만 연결한 잡담은 음성 클립으로 남깁니다. 새 클립은 게임 소리와 스트리머 음성을 따로 저장하여 재생 중 음성을 켜고 끌 수 있어요. 기존에 섞어 저장된 음성은 분리되지 않습니다. 약 15초 단위의 구간이 끝난 뒤 연결됩니다. 이 PC에 최대 100개·500MB.</p></section>
    <div className="clip-layout"><div className="clip-grid">{list.map(c=><button className={'panel clip-card '+(selected===c.id?'selected':'')} key={c.id} onClick={()=>{if(selected!==c.id)setClip(null);setSelected(c.id);setParent(null);setText('');}}><div className="clip-thumb">{c.thumbnail?<img src={`/api/clips/${c.id}/media/thumbnail`} alt=""/>:<Clapperboard size={35}/>}<span>{c.video?<><Play size={12}/> 영상</>:c.audio?<><Headphones size={12}/> 음성</>:'장면 기록'}</span></div><div><small>{c.day} · {c.game}</small><h3>{c.title}</h3><p><MessageCircle size={13}/> {c.commentCount} · 추천 {c.votes?.length||0} · {c.participants.map(p=>p.name).slice(0,3).join(', ')}</p></div></button>)}{!list.length&&<section className="panel feature-body"><h3>첫 핫클립을 기다려요</h3><p>관객이 개인적으로 좋아한 순간을 남기면 여기에 나타납니다. 화면 없이 나눈 대화도 핫클립이 될 수 있어요.</p></section>}</div>
    {clip&&<section className="panel feature-body clip-detail"><div className="section-actions"><h2>{clip.title}</h2><button className="icon" title="이 핫클립 삭제" disabled={pending} onClick={async()=>{if(await send('clips/'+clip.id,undefined,'DELETE')){setSelected(null);setClip(null);}}}><Trash2 size={16}/></button></div><ClipMedia clip={clip}/><p>{clip.scene}</p>{clip.creator&&<blockquote>{clip.creator.name}: {clip.creator.reason}</blockquote>}<div className="tags"><span>{clip.day}</span><span>{clip.game}</span><span>{clip.video?clip.hasAudio?'소리 포함':'소리 없는 영상':clip.audio?'화면 없는 음성 클립':'대화·화면 기록'}</span><span>{clip.creator?`${clip.creator.name}의 선택`:clip.source==='automatic-moment'?'이전 자동 명장면':clip.source==='directed-episode'?'기획 방송':'직접 저장'}</span></div><details><summary>그때의 채팅 {clip.messages.length}개</summary>{clip.messages.map(m=><div key={m.id}><p><b>{m.name}</b><DonationBadge donation={m.donation}/> {m.transcription?.correction?.text||m.text}</p>{m.transcription?.correction&&<details className="transcript-origin"><summary>음성 교정 · 인식 원문 보기</summary><p>{m.text}</p></details>}</div>)}</details><h3>이 순간에 남은 이야기 · 추천 {clip.votes?.length||0}</h3><Thread items={clip.comments} reply={setParent} remove={id=>void send(`clips/${clip.id}/comments/${id}`,undefined,'DELETE')}/>
      {parent&&<p className="reply-target">{parent.name}에게 답글 <button className="text-button" onClick={()=>setParent(null)}>취소</button></p>}<textarea aria-label="핫클립 댓글" value={text} maxLength={1000} onChange={e=>setText(e.target.value)} placeholder="이 순간에 대해 이야기해보세요..."/><button className="secondary" disabled={pending||!text.trim()} onClick={async()=>{if(await send(`clips/${clip.id}/comments`,{text,parentId:parent?.id||null})){setText('');setParent(null);}}}>댓글 남기기</button><p className="field-note">관객은 앱이 켜져 있을 때 스스로 들러 기록을 읽고 댓글·대댓글·추천을 결정합니다. 말없이 읽고 가기도 해요. 방송 응답을 우선하며, 자동 활동은 방송 설정에서 잠시 쉴 수 있습니다.</p>
    </section>}</div>
  </div>;
}
