import {useState} from 'react';
import {ArrowRight,BookOpen,Clapperboard,Mail,Mic,Pause,Play,Plus,Send,Sparkles,Ticket} from 'lucide-react';
import {api} from './api';
import type {State,Message} from './types';
import './seasons.css';
type Cast={id:string;name:string}[];
type Node={id:string;title:string;premise:string;stages:string[];choices:{id:string;label:string;next:string}[];keepsake:string|null};
type Template={id:string;title:string;tag:string;description:string;nodes:Node[]};
type Chapter={node:string;stage:number;startedAt:number|null;endedAt:number|null;cast:Cast;messages:Message[];messageCount:number};
type Season={id:string;templateId:string;title:string;premise:string;status:'open'|'completed';createdAt:number;updatedAt:number;chapters:Chapter[];decisions:{from:string;label:string;next:string;at:number}[];keepsake:string|null};
type Proposal={id:string;personaId:string;name:string;templateId:string;text:string;source:{excerpt:string;at:number};createdAt:number;status:string;snoozedUntil:number;seasonId:string|null};
export type SeasonsState={catalog:Template[];settings:{autoProposals:boolean};active:{id:string;cast:Cast}|null;seasons:Season[];proposals:Proposal[]};
export function Seasons({state,onError,onSay,onMic,mic}:{state:State;onError:(s:string)=>void;onSay:(s:string)=>void;onMic:()=>void;mic:boolean}){
  const world=state.seasons;
  const [selected,setSelected]=useState(''),[templateId,setTemplateId]=useState('our-room-v1'),[title,setTitle]=useState(''),[premise,setPremise]=useState(''),[line,setLine]=useState(''),[pending,setPending]=useState(false),[notice,setNotice]=useState(''),[creating,setCreating]=useState(!world.seasons.length),[confirmDelete,setConfirmDelete]=useState(''),[targets,setTargets]=useState<string[]>([]),[showSnoozed,setShowSnoozed]=useState(false),[inboxOpen,setInboxOpen]=useState(!world.seasons.length);
  const item=world.seasons.find(s=>s.id===(world.active?.id||selected))||world.seasons.at(-1),template=world.catalog.find(t=>t.id===(item?.templateId||templateId));
  const current=item?.chapters.at(-1),node=template?.nodes.find(n=>n.id===current?.node),active=!!item&&world.active?.id===item.id,locked=pending||state.busy;
  const present=state.settings.personas.filter(p=>p.enabled&&p.role!=='manager'&&p.id!==state.settings.managerId&&['active','lurking'].includes(state.audience.presence[p.id]));
  const request=async<T=unknown,>(path:string,body?:unknown,method?:string)=>{if(pending)return null;setPending(true);onError('');setNotice('');try{return await api<T>(path,body,method);}catch(e){onError(e instanceof Error?e.message:'시즌을 진행하지 못했습니다.');return null;}finally{setPending(false);}};
  const snoozed=world.proposals.filter(p=>p.status==='snoozed'&&p.snoozedUntil>Date.now());
  const invites=world.proposals.filter(p=>p.status==='suggested'||(p.status==='snoozed'&&(showSnoozed||p.snoozedUntil<=Date.now())));
  return <div className="season-world">
    <section className={"season-hero panel "+(world.seasons.length?"compact":"")}><div><div className="eyebrow">THE STORY CONTINUES</div><h2>오늘의 방송이 <br/>다음 만남의 이야기가 되도록.</h2><p>관객들이 건네는 초대장, 함께 정하는 다음 회차.<br/>현실의 규모를 넘어 상상하고, 우리만의 시즌으로 간직하세요.</p><div className="tags"><span>선택으로 달라지는 이야기</span><span>언제든 쉬었다 이어가기</span><span>관객마다 다른 목소리</span></div></div><div className="season-hero-mark" aria-hidden="true"><BookOpen size={54}/><span>OUR NEXT<br/>CHAPTER</span></div></section>
    <details className="panel season-inbox" open={inboxOpen} onToggle={e=>setInboxOpen(e.currentTarget.open)}><summary><Mail size={17}/> 관객의 초대장 <span>{invites.length?`${invites.length}개의 제안이 기다려요`:"대화에서 시작하는 다음 기획"}</span></summary><div className="season-section-heading"><div><span className="eyebrow">FROM YOUR AUDIENCE</span><h3><Mail size={18}/> 관객의 초대장 <small>{invites.length}</small></h3></div><button className="secondary" disabled={locked||!state.running||state.settings.mode!=='live'||!!world.active||!!state.director.active} onClick={()=>void request('seasons/propose')}><Sparkles size={15}/> 관객에게 기획 맡기기</button></div><p className="field-note">관객과 나눈 공개 대화에서 다음 기획이 시작돼요. 초대장 한 장에 모델 1회. 받아도 방송은 자동으로 시작되지 않아요.</p>
      <label className="season-auto"><input type="checkbox" checked={world.settings.autoProposals} disabled={pending} onChange={e=>void request('seasons/settings',{autoProposals:e.target.checked})}/> 방송 중 관객이 먼저 기획을 제안하도록 하기</label><p className="field-note">10분 이상, 공개 대화 20개 이후 여유 시간에 방송당 최대 1회 · 최소 1시간 간격. 세션 호출 한도를 공유하며 방송 종료 중에는 생성하지 않습니다.</p>
      {!!snoozed.length&&<button className="quiet" onClick={()=>setShowSnoozed(!showSnoozed)}>{showSnoozed?'미뤄둔 초대장 접기':`미뤄둔 초대장 ${snoozed.length}개 보기`}</button>}
      {!invites.length?<div className="season-empty"><Mail size={22}/><p>아직 도착한 초대장이 없어요.<br/><small>오늘 관객들과 나눈 이야기에서 다음 방송의 씨앗을 찾아보세요.</small></p></div>:<div className="season-invites">{invites.map(p=><article className="season-invite" key={p.id}><small>{p.name}에게서 · {new Date(p.createdAt).toLocaleDateString('ko-KR')}{p.status==='snoozed'&&` · ${new Date(p.snoozedUntil).toLocaleDateString('ko-KR')}에 다시 보기`}</small><h4>{world.catalog.find(t=>t.id===p.templateId)?.title}</h4><p>{p.text}</p><details><summary>이 제안이 시작된 대화</summary><blockquote>{p.source.excerpt}</blockquote><small>{new Date(p.source.at).toLocaleString('ko-KR')} · 이 방송의 공개 채팅</small></details><div className="feature-buttons"><button className="primary" disabled={locked} onClick={async()=>{const result=await request<Season>('seasons/respond',{id:p.id,action:'accept'});if(result){setSelected(result.id);setCreating(false);setNotice('초대장을 시즌으로 간직했어요. 원하는 날 첫 회차를 열어주세요.');}}}>시즌으로 간직하기</button><button className="secondary" disabled={locked} onClick={()=>void request('seasons/respond',{id:p.id,action:'snooze'})}>내일 다시 보기</button><button className="quiet" disabled={locked} onClick={()=>void request('seasons/respond',{id:p.id,action:'decline'})}>이번엔 괜찮아</button></div></article>)}</div>}
    </details>
    <div className="season-section-heading"><h3><BookOpen size={18}/> 우리 방 시즌 서가 <small>{world.seasons.length}/12</small></h3><button className="secondary" onClick={()=>setCreating(!creating)} disabled={!!world.active}><Plus size={16}/>{creating?'기획 접기':'새 시즌 기획'}</button></div>
    {creating&&<section className="panel season-create"><div className="season-templates">{world.catalog.map(t=><button key={t.id} className={'season-template '+(templateId===t.id?'selected':'')} onClick={()=>setTemplateId(t.id)}><small>{t.tag}</small><h3>{t.title}</h3><p>{t.description}</p><span>3회차 · 9장면 · 두 가지 피날레 <ArrowRight size={14}/></span></button>)}</div><div className="season-form"><label>시즌 이름<input maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder={world.catalog.find(t=>t.id===templateId)?.title}/></label><label>함께 만들고 싶은 세계<textarea aria-label="시즌 설정" maxLength={1200} value={premise} onChange={e=>setPremise(e.target.value)} placeholder="예: 우리 관객들이 우주선 크루라는 설정. 나는 실수 많은 선장이고, 결말은 엄청 따뜻했으면 좋겠어."/></label><button className="primary" disabled={locked||world.seasons.length>=12} onClick={async()=>{const result=await request<Season>('seasons',{templateId,title,premise});if(result){setSelected(result.id);setCreating(false);setInboxOpen(false);setTitle('');setPremise('');setTargets([]);}}}><Plus size={16}/> 시즌 서가에 놓기</button><p className="field-note">기획·선택·저장에는 모델 호출이 없습니다. 회차 진행과 자유 대화에서 호출을 사용해요.</p></div></section>}
    {notice&&<p role="status" className="saved-note">{notice}</p>}
    {!!world.seasons.length&&<div className="season-layout"><nav className="season-shelf" aria-label="내 시즌 목록">{world.seasons.slice().reverse().map(s=><button className={'panel season-book '+(item?.id===s.id?'selected':'')} key={s.id} disabled={!!world.active&&world.active.id!==s.id} onClick={()=>{setSelected(s.id);setTargets([]);setLine('');setConfirmDelete('');}}><small>{s.status==='completed'?'피날레 완료':`${s.chapters.length}회차에서 이어가기`}</small><h3>{s.title}</h3><p>{s.premise||world.catalog.find(t=>t.id===s.templateId)?.description}</p><span>{new Date(s.updatedAt).toLocaleDateString('ko-KR')}{s.keepsake&&<Ticket size={16}/>}</span></button>)}</nav>
      {item&&current&&node&&<section className="panel season-stage"><div className="season-section-heading"><div><small>{item.title}</small><h2>{item.chapters.length}화 · {node.title}</h2></div><span className="status-pill">{item.status==='completed'?'시즌 완결':active?'함께하는 중':'다음 만남을 기다려요'}</span></div><p>{node.premise}</p>{!!item.premise&&<blockquote>{item.premise}</blockquote>}
        <ol className="season-route">{item.chapters.map((c,i)=><li key={c.node} className={i===item.chapters.length-1?'current':''}><span>{i+1}</span><div><b>{template?.nodes.find(n=>n.id===c.node)?.title}</b>{item.decisions[i]&&<small>“{item.decisions[i].label}”을 선택했어요</small>}</div></li>)}</ol>
        {item.status==='completed'?<div className="season-keepsake"><Ticket size={30}/><small>함께 만든 시즌의 기념품</small><h3>{item.keepsake}</h3><p>다른 길이 궁금하다면 새 시즌을 열어보세요.<br/>이 이야기와 선택은 서가에 그대로 남아요.</p></div>:<>
          <ol className="episode-steps">{node.stages.map((label,i)=><li key={label} className={current.stage===i?'current':current.stage>i?'done':''}><span>{i+1}</span>{label}</li>)}</ol>
          {!active?<><p className="field-note">앱을 다시 열어도 마지막 장면에서 이어집니다. 이번 회차의 관객은 지금 함께하는 사람들로 고를 수 있어요.</p>{!state.running?<>{state.settings.mode!=='live'&&<p className="field-note">리허설 모드에서는 AI 방송을 시작할 수 없어요. 방송 설정에서 방송 모드를 ‘실제 AI 관객 · ChatGPT 구독’으로 바꾸면 시즌을 이어갈 수 있어요.</p>}<button className="primary" disabled={locked||!!state.training.active||state.settings.mode!=='live'} onClick={()=>void request('start')}><Play size={15}/> AI 방송 시작</button></>:<><fieldset className="season-cast"><legend>이번에 함께할 관객 · 미선택 시 최대 6명 자동</legend>{present.map(p=><label key={p.id}><input type="checkbox" checked={targets.includes(p.id)} disabled={locked||(!targets.includes(p.id)&&targets.length>=8)} onChange={e=>setTargets(e.target.checked?[...targets,p.id]:targets.filter(id=>id!==p.id))}/>{p.name}</label>)}</fieldset><button className="primary" disabled={locked||!!state.director.active||!present.length} onClick={()=>void request('seasons/resume',{id:item.id,...(targets.length?{targets}: {})})}><Play size={15}/>{current.stage<0?'이 회차 열기':'멈춘 장면에서 이어가기'}</button>{!!state.director.active&&<p className="field-note">기획 방송을 마무리하면 시즌을 이어갈 수 있어요.</p>}</>}</>:<>
            <p className="field-note">{world.active?.cast.map(p=>p.name).join(' · ')}</p><div className="episode-chat" aria-label="시즌 채팅" aria-live="polite">{current.messages.length?current.messages.map(m=><p key={m.id}><b style={{color:m.color}}>{m.name}</b> {m.text}</p>):<p className="muted">첫 장면을 열면 관객들과 이야기가 시작돼요.</p>}</div><label>이번 장면에서 하고 싶은 말<textarea aria-label="시즌 진행 멘트" value={line} maxLength={1200} onChange={e=>setLine(e.target.value)} placeholder="선장으로서 한마디 할게. 우리 목적지는 따뜻한 별이야!"/></label><div className="feature-buttons"><button className="secondary" disabled={locked||!line.trim()} onClick={()=>{onSay(line.trim());setLine('');}}><Send size={14}/> 관객과 이야기</button><button className={'secondary '+(mic?'active':'')} onClick={onMic}><Mic size={14}/>{mic?'마이크 끄기':'마이크로 이야기'}</button>{current.stage<2&&<button className="primary" disabled={locked} onClick={async()=>{if(await request('seasons/advance',{text:line}))setLine('');}}><Sparkles size={15}/>{current.stage<0?'첫 장면 열기':'다음 장면 열기'} · 1회</button>}<button className="secondary" disabled={pending} onClick={()=>void request('seasons/pause')}><Pause size={14}/> 여기서 쉬어가기</button></div><p className="field-note">이야기는 가상 연출로 기록됩니다. 연출한 승리나 호응으로 게임 지식·포인트 후원이 쌓이지 않습니다.</p>
          </>}
          {current.stage===2&&<div className="season-choices"><h3>{node.choices.length?'다음 회차, 어디로 갈까요?':'이 시즌의 마지막 페이지'}</h3><p>{node.choices.length?'선택한 길이 다음 회차가 됩니다. 오늘 계속해도, 다음 방송에 이어가도 좋아요.':'관객들과 나눈 이야기를 닫고 우리만의 기념품을 남겨요.'}</p>{node.choices.length?node.choices.map(c=><button className="secondary" key={c.id} disabled={locked} onClick={()=>void request('seasons/choose',{id:item.id,choiceId:c.id})}>{c.label}<ArrowRight size={15}/></button>):<button className="primary" disabled={locked} onClick={()=>void request('seasons/choose',{id:item.id})}><Ticket size={15}/> 피날레 · 기념품 남기기</button>}</div>}
        </>}
        <details className="season-chronicle"><summary>함께 만든 회차 기록</summary>{item.chapters.map(c=><article key={c.node}><small>{c.startedAt?new Date(c.startedAt).toLocaleString('ko-KR'):'아직 열지 않은 회차'} · {c.messageCount}개의 대화</small><h4>{template?.nodes.find(n=>n.id===c.node)?.title}</h4><p>{c.cast.map(p=>p.name).join(' · ')}</p>{c.messages.slice(-6).map(m=><p key={m.id}><b>{m.name}</b> {m.text}</p>)}{!!c.endedAt&&<button className="secondary" disabled={locked} onClick={async()=>{if(await request('seasons/clip',{id:item.id,nodeId:c.node}))setNotice('핫클립에 회차를 남겼어요. 다른 관객과 댓글을 이어갈 수 있습니다.');}}><Clapperboard size={15}/> 회차 핫클립 남기기</button>}</article>)}</details>
        {!active&&<details className="season-manage"><summary>시즌 보관 관리</summary><p className="field-note">전체 기록은 방송실의 내보내기에 포함됩니다. 삭제하면 이 시즌과 연결된 초대장이 사라져요. 이미 남긴 핫클립은 별도로 관리합니다.</p>{confirmDelete===item.id?<div><button className="danger" disabled={locked} onClick={async()=>{if(await request(`seasons/${item.id}`,undefined,'DELETE')){setSelected('');setConfirmDelete('');}}}>이 시즌 기록 삭제</button><button className="quiet" onClick={()=>setConfirmDelete('')}>취소</button></div>:<button className="quiet" disabled={locked} onClick={()=>setConfirmDelete(item.id)}>시즌 삭제…</button>}</details>}
      </section>}
    </div>}
  </div>;
}
