import {useState} from 'react';
import {Coins,Heart,Brain,Network,Gift,Sparkles} from 'lucide-react';
import {api} from './api';
import catalog from '../shared/economy.json';
import type {State,Message} from './types';

export type FeatureResult={kind:string;title:string;at:number;personaId:string;note:string;origin?:string;values?:string;personality?:string;sociability?:number;expertise?:number;sessions?:number;seconds?:number;recognized?:number;affinity?:number;memories?:string[];preferences?:{at:number;question:string;answers:string[]}[];peers?:{id:string;name:string;outgoing:number;incoming:number}[];question?:string;sourceMessage?:Message;messages?:{personaId:string;name:string;text:string}[]};
export type Receipt={id:string;kind:string;key:string;cost:number;status:string;at:number;error?:string;result?:FeatureResult};
export type Quote={id:string;kind:string;text:string;targets:string[];ask:number;agreed?:number;status:string;round:number;expiresAt:number;history:{speaker:string;text:string;amount?:number}[]};
export type EconomyState={balance:number;wallets:Record<string,{balance:number;cap:number;nextRefillAt:number|null}>;ledger:{id:string;at:number;kind:string;amount:number;text:string;name?:string;personaId?:string}[];quotes:Quote[];purchases:Receipt[];rules:typeof catalog};
function ResultCard({value}:{value:FeatureResult}){
  return <article className="panel feature-result"><div className="panel-heading"><b>{value.title}</b><span className="status-pill">스트리머 전용</span></div><div className="feature-body"><small>{new Date(value.at).toLocaleString('ko-KR')}</small>
    {value.sourceMessage&&<blockquote>{value.sourceMessage.name} “{value.sourceMessage.text}”</blockquote>}
    {value.kind==='profile'&&<><h3>{value.origin}</h3><p>{value.personality}</p><div className="tags"><span>사교성 {Math.round((value.sociability||0)*100)}%</span><span>숙련도 {Math.round((value.expertise||0)*100)}%</span><span>함께한 방송 {value.sessions}회</span><span>시청 {Math.floor((value.seconds||0)/60)}분</span></div><h4>중요하게 여기는 것</h4><p>{value.values}</p><h4>최근 직접 한 말</h4>{value.memories?.map((m,i)=><p key={i}>“{m}”</p>)}</>}
    {value.kind==='profile'&&!!value.preferences?.length&&<><h4>이전에 나눈 취향 이야기</h4>{value.preferences.map((p,i)=><div className="private-preference" key={i}><small>{new Date(p.at).toLocaleDateString('ko-KR')}</small><b>{p.question}</b>{p.answers.map((answer,j)=><p key={j}>{answer}</p>)}</div>)}</>}
    {value.kind==='relations'&&<><div className="relationship-core"><Heart size={27}/><strong>스트리머 친밀도 {Math.round((value.affinity||0)*100)}%</strong><span>호명 받은 대화 {value.recognized}회</span></div>{!value.peers?.length&&<p>아직 관객끼리 이름을 부른 대화가 없어요. 함께하는 시간이 쌓이면 관계가 드러납니다.</p>}{value.peers?.map(p=><div className="relation-row" key={p.id}><b>{p.name}</b><span>이 관객에게 말함 {p.outgoing}회 →</span><span>이름을 불러줌 {p.incoming}회 ←</span></div>)}</>}
    {value.messages?.map((m,i)=><div className="private-dialogue" key={i}><b>{m.name}</b><p>{m.text}</p></div>)}<p className="field-note">{value.note}</p></div></article>;
}
export function DonationToast({economy}:{economy:EconomyState}){const recent=economy.ledger.filter(e=>e.kind==='donation'&&Date.now()-e.at<12000).slice(-2);return <div className="donation-toasts">{recent.map(e=><div className="donation-toast" key={e.id}><Gift size={24}/><div><b>{e.name} · {e.amount}P</b><p>{e.text}</p><small>가상 후원 · 현금 이동 없음</small></div></div>)}</div>;}
export function SpecialStudio({state,focusMessage,onError}:{state:State;focusMessage:Message|null;onError:(text:string)=>void}){
  const [target,setTarget]=useState(focusMessage?.personaId || state.settings.personas[0].id),[question,setQuestion]=useState('어떤 방송 순간을 가장 좋아하고, 어떤 분위기는 조금 불편해요?'),[result,setResult]=useState<FeatureResult|null>(null),[pending,setPending]=useState(false);
  const [actionKind,setActionKind]=useState('cheer'),[request,setRequest]=useState('오늘 도전한 저에게 각자 한 마디씩 응원해주세요.'),[targets,setTargets]=useState<string[]>([]),[offers,setOffers]=useState<Record<string,number>>({});
  const e=state.economy,person=state.settings.personas.find(p=>p.id===target),wallet=e.wallets[target],met=!!state.audience.members[target]?.sessions;
  const chat=(focusMessage?.personaId===target?focusMessage:null) || state.messages.filter(m=>m.kind==='chat'&&m.personaId===target).at(-1);
  async function send(path:string,body:unknown){setPending(true);onError('');try{const reply=await api<Receipt>(path,body);if(reply.result)setResult(reply.result);return reply;}catch(error){onError(error instanceof Error?error.message:'기능 실행 실패');}finally{setPending(false);}}
  const allowed=state.settings.pointsEnabled&&state.settings.mode==='live';
  const completed=e.purchases.filter(p=>p.status==='completed'&&p.result).slice().reverse();
  return <div className="special-studio"><section className="points-hero panel"><div><span className="eyebrow">YOUR AUDIENCE, A LITTLE CLOSER</span><h2>채팅 너머의 마음을 만나보세요.</h2><p>멋진 순간에 받은 가상 후원으로, 관객을 더 깊이 알아가는 시간.</p></div><div className="point-balance"><Coins size={24}/><strong>{e.balance.toLocaleString()}<small>P</small></strong><span>현금 가치 · 구매 · 환전 없음</span></div></section>
    {!allowed&&<p className="alert">실제 AI 관객 모드와 가상 포인트 기능을 켜면 이용할 수 있습니다.</p>}
    <div className="special-columns"><div><section className="panel feature-body"><label>알아보고 싶은 관객<select value={target} onChange={ev=>setTarget(ev.target.value)}>{state.settings.personas.map(p=><option key={p.id} value={p.id}>{p.name}{state.audience.members[p.id]?.sessions?'':' · 아직 만나지 않음'}</option>)}</select></label><div className="wallet-strip"><b>{person?.name}의 지갑</b><span>{wallet?.balance || 0} / {wallet?.cap || 200}P</span></div><p className="field-note">관객 지갑은 현실 시간 1분마다 1P 충전됩니다. 앱이 꺼져 있던 시간도 반영하며 최대 200P입니다.</p>
      <div className="feature-buttons"><button className="secondary" disabled={!allowed||!met||pending} onClick={()=>void send('special/unlock',{kind:'profile',personaId:target,requestId:crypto.randomUUID()})}><Heart size={17}/> 상세 수첩 · {catalog.prices.profile}P</button><button className="secondary" disabled={!allowed||!met||pending} onClick={()=>void send('special/unlock',{kind:'relations',personaId:target,requestId:crypto.randomUUID()})}><Network size={17}/> 관계 지도 · {catalog.prices.relations}P</button></div><p className="field-note">관객별 수첩·관계 지도는 한 번 열면 다시 볼 때 무료입니다.</p>
      <h3><Brain size={17}/> 이 채팅의 속마음</h3><blockquote>{chat?`${chat.name}: ${chat.text}`:'방송실의 관객 채팅에서 속마음 버튼을 누르거나, 대화 후 관객을 선택하세요.'}</blockquote><button className="secondary" disabled={!allowed||!chat||pending||state.busy} onClick={()=>void send('special/generate',{kind:'thought',messageId:chat?.id,requestId:crypto.randomUUID()})}>창작 독백 보기 · {catalog.prices.thought}P</button>
      <h3><Sparkles size={17}/> 취향 인터뷰</h3><textarea aria-label="관객 취향 질문" value={question} maxLength={600} onChange={ev=>setQuestion(ev.target.value)}/><button className="primary" disabled={!allowed||!met||pending||state.busy||!question.trim()} onClick={()=>void send('special/generate',{kind:'interview',personaId:target,question,requestId:crypto.randomUUID()})}>{pending?'대답을 기다리는 중':'질문하기 · '+catalog.prices.interview+'P'}</button><p className="field-note">독백·인터뷰·합의한 행동은 모델 1회 사용. 실패하거나 취소되면 포인트를 돌려드립니다.</p>
    </section>{result&&<ResultCard value={result}/>}</div>
    <section className="panel feature-body negotiation"><h2>관객에게 부탁하기</h2><p>관객의 성향과 친밀도에 따라 요구 가격이 달라져요. 역제안하거나 다음을 기약할 수 있습니다.</p><label>어떤 행동인가요?<select value={actionKind} onChange={ev=>setActionKind(ev.target.value)}>{Object.entries(catalog.actions).map(([key,a])=><option value={key} key={key}>{a.label}</option>)}</select></label><textarea aria-label="관객 행동 부탁" maxLength={600} value={request} onChange={ev=>setRequest(ev.target.value)}/><div className="target-pills">{state.settings.personas.filter(p=>p.enabled&&p.id!==state.settings.managerId).map(p=><label key={p.id}><input type="checkbox" checked={targets.includes(p.id)} disabled={!['active','lurking'].includes(state.audience.presence[p.id])} onChange={ev=>setTargets(ev.target.checked?[...targets,p.id].slice(0,8):targets.filter(id=>id!==p.id))}/>{p.name}</label>)}</div><button className="secondary" disabled={!allowed||!state.running||!targets.length||pending||!request.trim()} onClick={()=>void send('special/quote',{targets,kind:actionKind,text:request})}>요구 가격 물어보기</button><p className="field-note">견적·역제안은 무료. 현재 시청 중인 최대 8명에게 한 번의 채팅 행동을 부탁합니다.</p>
    {e.quotes.slice().reverse().slice(0,5).map(q=><article className="quote-card" key={q.id}><div className="inline-form"><b>{catalog.actions[q.kind as keyof typeof catalog.actions]?.label}</b><span className="status-pill">{{open:'협상 중',agreed:'합의됨',completed:'실행 완료',declined:'거절',expired:'만료',cancelled:'취소',executing:'실행 중',failed:'반환됨'}[q.status] || q.status}</span></div><p>{q.text}</p>{q.history.map((h,i)=><p className={h.speaker==='관객'?'audience-offer':''} key={i}><b>{h.speaker}</b> {h.text}</p>)}
      {q.status==='open'&&<div className="inline-form"><input aria-label="역제안 포인트" type="number" min={1} max={10000} value={offers[q.id]??q.ask} onChange={ev=>setOffers({...offers,[q.id]:Number(ev.target.value)})}/><button className="secondary" disabled={pending} onClick={()=>void send('special/bid',{id:q.id,amount:offers[q.id]??q.ask})}>가격 제안</button></div>}
      {q.status==='agreed'&&<button className="primary" disabled={pending||state.busy||!state.running} onClick={()=>void send('special/generate',{kind:'contract',quoteId:q.id,requestId:crypto.randomUUID()})}>합의한 행동 실행 · {q.agreed}P</button>}{['open','agreed'].includes(q.status)&&<button className="text-button" disabled={pending} onClick={()=>void send('special/cancel',{id:q.id})}>협상 취소</button>}</article>)}
    </section></div>
    <section className="panel feature-body"><h2>열어본 마음과 관계</h2><div className="feature-buttons">{completed.map(p=><button className="secondary" key={p.id} onClick={()=>setResult(p.result!)}>{state.settings.personas.find(v=>v.id===p.result?.personaId)?.name} · {p.result?.title}</button>)}</div>{!completed.length&&<p className="muted">관객의 마음을 알아가면 여기에 기록이 쌓여요.</p>}</section>
    <section className="panel feature-body"><h2>포인트 기록</h2><p className="field-note">최초 체험 60P. 강한 긍정적 순간에서만 가상 후원이 발생하며 관객별 10분 간격, 전체 1시간 240P 제한이 있습니다. 구매한 연출은 즉시 후원으로 되돌아오지 않습니다.</p>{e.ledger.slice(-30).reverse().map(l=><div className="point-entry" key={l.id}><span>{new Date(l.at).toLocaleTimeString('ko-KR')}</span><p>{l.name&&`${l.name} · `}{l.text}</p><b>{l.amount>0?'+':''}{l.amount}P</b></div>)}</section>
  </div>;
}
