import type {TrainingState} from './Training';
import type {DirectorState} from './Experiences';
import type {ClipSummary} from './HotClips';
import type {EconomyState} from './SpecialStudio';
import type {SeasonsState} from './Seasons';
export type Persona={id:string;name:string;color:string;role:'viewer'|'manager';personality?:string;enabled:boolean;sociability?:number;expertise?:number;values?:string;system?:boolean;profileUnlocked?:boolean};
export type Game={id:string;name:string;genre:string;context:string;popularity:number};
export type DiscoverySettings={enabled:boolean;arrivalSeconds:number;mix:{clip:number;guide:number;fan:number;discussion:number;browse:number}};
export type Settings={contextualTranscription:boolean;showStreamerMessages:boolean;clipBufferEnabled:boolean;autoHighlights:boolean;pointsEnabled:boolean;discovery:DiscoverySettings;title:string;streamer:string;gameId:string;mode:'live'|'rehearsal';category:'gaming'|'just-chatting';crowdStyle:'cozy'|'lively'|'stadium';lurkRatio:number;communityCulture:string;streamerStyle:string;adviceMode:'on-request'|'always'|'never';webSearch:boolean;mistakenAdvice:number;attentionSeeking:number;intervalSeconds:number;maxCalls:number;chatPace:number;managerId:string;managerRules:string;blockedWords:string[];slowModeSeconds:number;spoilerGuard:boolean;personas:Persona[];games:Game[]};
export type Message={donation?:{amount:number;anonymous:boolean};transcription?:{source:"microphone";correction?:{text:string;confidence:number;reason:string;at:number}};id:string;personaId:string;name:string;color:string;text:string;kind:string;time:number};
export type SoundState={connected:boolean;busy:boolean;source:string;last:null|{endedAt:number;silent:boolean;volumeDb:number;classes:{label:string;score:number;peak:number}[];systemSpeech:string}};
export type State={autonomy?:{pending:boolean;price:number;broadcastSeconds:number;maxViewers:number};ambient?:{active:null|{id:string;title:string};quiet:boolean};sound?:SoundState;journal?:{revision:number;count:number;pinned:number;limit:number;pinLimit:number};onboarding?:{version:1;status:'new'|'completed'|'existing'|'skipped';completedAt:number|null};connectionProbe?:ProbeState;storage:{warnings:string[];recovered:string[]};training:TrainingState;director:DirectorState;seasons:SeasonsState;clips:ClipSummary[];economy:EconomyState;settings:Settings;audience:{presence:Record<string,string>;members:Record<string,{sessions:number;seconds:number;note?:string;aliases:{name:string;at:number}[];recognized?:number;affinity?:number;origin?:{key:string;label:string;firstSeenAt:number};joinedAt?:number}>;lore:{text:string;expiresAt:number}[];posts:{id:string;name:string;text:string;time:number;kind:string}[]};running:boolean;sessionId:string;startedAt:number|null;messages:Message[];events:{id:string;time:number;text:string}[];observation:{game:string;scene:string;confidence:number;excitement:number;at:number}|null;calls:number;tokens:number;busy:boolean;lastError:string;queued:number;knowledge:{name:string;seconds:number;observations:{id:string;text:string;at:number}[];notes:{id:string;text:string;at:number}[]}[];provider:{configured:boolean;model:string;effort:string;kind?:string;authMessage?:string;authState?:string;audioError?:string;audioConfigured?:boolean;transcriptionModel:string;localAudio?:boolean}};
export type Source={id:string;name:string;kind?:'screen'|'window';thumbnail:string};
export type AccountState={status:'idle'|'checking'|'starting'|'waiting'|'connected'|'failed'|'cancelling'|'cancelled'|'expired';method?:'browser'|'device';url?:string;code?:string;expiresAt?:number;message?:string};
export type ProbeState={status:'untested'|'checking'|'ready'|'failed'|'cancelled';startedAt?:number;checkedAt?:number;latencyMs?:number;model?:string;effort?:string;reply?:string;tokens?:number;reason?:string;message?:string};
declare global { interface Window {backseat?:{sources:()=>Promise<Source[]>;sourcePreviews?:(type:'screen'|'window')=>Promise<Source[]>;selectSource:(id:string,systemAudio?:boolean)=>Promise<void>;openOverlay:()=>Promise<void>;toggleClickThrough:()=>Promise<boolean>;closeOverlay:()=>Promise<void>;onOverlayState:(fn:(value:boolean)=>void)=>()=>void;onPanic:(fn:()=>void)=>()=>void;accountStatus:()=>Promise<AccountState>;startAccountLogin:(method:'browser'|'device')=>Promise<AccountState>;cancelAccountLogin:()=>Promise<AccountState>;openAccountLogin:()=>Promise<void>;onAccountState:(fn:(value:AccountState)=>void)=>()=>void};} }

