; installer/common.nsh
; ---------------------------------------------------------------------------
; Shared, reviewable NSIS logic for the Nagneon *per-user* installer.
;
; Design invariants enforced here (see docs/INSTALLER.md for the full rationale):
;   * No plugins are required (core NSIS + LogicLib only).
;   * The installer never elevates and never writes machine-wide state.
;   * The installer never kills processes and never silently restarts a
;     running broadcast. A running old version lives in its own versioned
;     folder, so extraction of a new version cannot touch it.
;   * The uninstaller removes ONLY files it installed (manifest-listed, owned
;     relative paths). It never runs `RMDir /r` against an install directory,
;     so unknown / user-created / locked files are always left in place.
;
; This file is STATIC. Per-build file lists (the exact owned payload) are
; generated by scripts/build-installer.mjs and !included by the rendered .nsi.
; ---------------------------------------------------------------------------

!ifndef BACKSEAT_COMMON_NSH
!define BACKSEAT_COMMON_NSH

!include "LogicLib.nsh"

; Fail the *compile* early if the driving .nsi forgot a required identity
; define. This is the first line of defence against generating an installer
; with a blank AppId / install root / shortcut group.
!macro BACKSEAT_REQUIRE NAME
  !ifndef ${NAME}
    !error "BACKSEAT installer: required define `${NAME}` is missing"
  !endif
!macroend

; Per-user context for every file/registry/shortcut operation:
;   * SetShellVarContext current  -> $SMPROGRAMS = per-user Start Menu,
;                                     $LOCALAPPDATA available, no elevation.
; Must be called in both .onInit and un.onInit.
!macro BACKSEAT_INIT_CONTEXT
  SetShellVarContext current
!macroend

; Write the Add/Remove Programs (Apps & features) entry under HKCU only.
; Publisher intentionally stays a development marker until a real, signed
; publisher is configured. Nothing here claims the build is signed.
; Call ONLY after the payload has been successfully promoted.
!macro BACKSEAT_WRITE_UNINSTALL_INFO
  WriteRegStr   HKCU "${REG_UNINSTALL_KEY}" "DisplayName"     "${APP_NAME}"
  WriteRegStr   HKCU "${REG_UNINSTALL_KEY}" "DisplayVersion"  "${APP_VERSION}"
  WriteRegStr   HKCU "${REG_UNINSTALL_KEY}" "Publisher"       "${PUBLISHER}"
  WriteRegStr   HKCU "${REG_UNINSTALL_KEY}" "DisplayIcon"     "$PayloadDir\${EXE_NAME}"
  WriteRegStr   HKCU "${REG_UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr   HKCU "${REG_UNINSTALL_KEY}" "UninstallString" '"$INSTDIR\${UNINSTALLER_NAME}"'
  WriteRegStr   HKCU "${REG_UNINSTALL_KEY}" "AppId"           "${APP_ID}"
  WriteRegDWORD HKCU "${REG_UNINSTALL_KEY}" "NoModify"        1
  WriteRegDWORD HKCU "${REG_UNINSTALL_KEY}" "NoRepair"        1
  WriteRegDWORD HKCU "${REG_UNINSTALL_KEY}" "EstimatedSize"   ${ESTIMATED_SIZE_KB}
!macroend

; Remove the HKCU Add/Remove Programs entry. Owned key only.
!macro BACKSEAT_DELETE_UNINSTALL_INFO
  DeleteRegKey HKCU "${REG_UNINSTALL_KEY}"
!macroend

!endif ; BACKSEAT_COMMON_NSH
